on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_artifacts
        with:
          route: GET /repos/{repository}/actions/runs/{run_id}/artifacts
          repository: ${{ github.repository }}
          run_id: ${{ github.event.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest artifacts: '${{ steps.get_artifacts.outputs.data }}'"
